M48
; DRILL file {KiCad 9.0.2} date 2025-07-02T14:38:04-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-07-02T14:38:04-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.750
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.000
%
G90
G05
T1
X5.0Y-5.0
X105.0Y-105.0
T2
X5.994Y-80.013
X5.994Y-103.012
X63.994Y-80.013
X63.994Y-103.012
T3
X6.503Y-18.74
X103.428Y-91.202
M30
